/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'MIMXRT6XX_EVK_SDHC' 
 * Target:  'MIMXRT6XX_EVK_SDHC' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM33.h"



#endif /* RTE_COMPONENTS_H */
