/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'MIMXRT1180_FLEXSPI' 
 * Target:  'MIMXRT1180_FPGA_FLEXSPI' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM33.h"



#endif /* RTE_COMPONENTS_H */
